/* eslint-disable */
/* AUTO-GENERATED nestify adapter stub for 'openclaw/plugin-sdk/channel-outbound'. Do not edit by hand.
 * Regenerate with: npm run gen:adapter
 * Add the marker @nestify-real to a hand-written replacement to preserve it. */
import { makeStub, type StubAny } from './__stub';

export const ChannelIngressQueue: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#ChannelIngressQueue');
export type ChannelIngressQueue<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const ChannelIngressQueueClaim: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#ChannelIngressQueueClaim');
export type ChannelIngressQueueClaim<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const ChannelIngressQueueClaimRef: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#ChannelIngressQueueClaimRef');
export type ChannelIngressQueueClaimRef<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const ChannelIngressQueueRecord: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#ChannelIngressQueueRecord');
export type ChannelIngressQueueRecord<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const ChannelMessageSendResult: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#ChannelMessageSendResult');
export type ChannelMessageSendResult<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const ChannelProgressDraftLine: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#ChannelProgressDraftLine');
export type ChannelProgressDraftLine<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const DurableMessageBatchSendResult: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#DurableMessageBatchSendResult');
export type DurableMessageBatchSendResult<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const MessageAckPolicy: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#MessageAckPolicy');
export type MessageAckPolicy<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const MessageReceipt: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#MessageReceipt');
export type MessageReceipt<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const MessageReceiptPartKind: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#MessageReceiptPartKind');
export type MessageReceiptPartKind<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const MessageReceiptSourceResult: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#MessageReceiptSourceResult');
export type MessageReceiptSourceResult<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const MessageReceiveContext: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#MessageReceiveContext');
export type MessageReceiveContext<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const OutboundDeliveryFormattingOptions: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#OutboundDeliveryFormattingOptions');
export type OutboundDeliveryFormattingOptions<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const OutboundSendDeps: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#OutboundSendDeps');
export type OutboundSendDeps<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const StreamingMode: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#StreamingMode');
export type StreamingMode<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const buildChannelProgressDraftLineForEntry: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#buildChannelProgressDraftLineForEntry');
export type buildChannelProgressDraftLineForEntry<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const buildOutboundSessionContext: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#buildOutboundSessionContext');
export type buildOutboundSessionContext<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createAccountStatusSink: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createAccountStatusSink');
export type createAccountStatusSink<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createChannelMessageAdapterFromOutbound: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createChannelMessageAdapterFromOutbound');
export type createChannelMessageAdapterFromOutbound<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createChannelMessageReplyPipeline: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createChannelMessageReplyPipeline');
export type createChannelMessageReplyPipeline<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createChannelProgressDraftGate: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createChannelProgressDraftGate');
export type createChannelProgressDraftGate<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createDurableInboundReceiveJournalFromQueue: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createDurableInboundReceiveJournalFromQueue');
export type createDurableInboundReceiveJournalFromQueue<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createFinalizableDraftStreamControlsForState: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createFinalizableDraftStreamControlsForState');
export type createFinalizableDraftStreamControlsForState<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createMessageReceiptFromOutboundResults: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createMessageReceiptFromOutboundResults');
export type createMessageReceiptFromOutboundResults<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createMessageReceiveContext: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createMessageReceiveContext');
export type createMessageReceiveContext<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createOutboundPayloadPlan: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createOutboundPayloadPlan');
export type createOutboundPayloadPlan<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const createPreviewMessageReceipt: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#createPreviewMessageReceipt');
export type createPreviewMessageReceipt<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const defineChannelMessageAdapter: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#defineChannelMessageAdapter');
export type defineChannelMessageAdapter<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const deliverInboundReplyWithMessageSendContext: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#deliverInboundReplyWithMessageSendContext');
export type deliverInboundReplyWithMessageSendContext<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const deriveDurableFinalDeliveryRequirements: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#deriveDurableFinalDeliveryRequirements');
export type deriveDurableFinalDeliveryRequirements<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const formatChannelProgressDraftLine: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#formatChannelProgressDraftLine');
export type formatChannelProgressDraftLine<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const formatChannelProgressDraftLineForEntry: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#formatChannelProgressDraftLineForEntry');
export type formatChannelProgressDraftLineForEntry<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const formatChannelProgressDraftText: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#formatChannelProgressDraftText');
export type formatChannelProgressDraftText<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const isChannelProgressDraftWorkToolName: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#isChannelProgressDraftWorkToolName');
export type isChannelProgressDraftWorkToolName<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const isPotentialTruncatedFinal: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#isPotentialTruncatedFinal');
export type isPotentialTruncatedFinal<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const listMessageReceiptPlatformIds: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#listMessageReceiptPlatformIds');
export type listMessageReceiptPlatformIds<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const mergeChannelProgressDraftLine: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#mergeChannelProgressDraftLine');
export type mergeChannelProgressDraftLine<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const projectOutboundPayloadPlanForDelivery: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#projectOutboundPayloadPlanForDelivery');
export type projectOutboundPayloadPlanForDelivery<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelMessageSourceReplyDeliveryMode: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelMessageSourceReplyDeliveryMode');
export type resolveChannelMessageSourceReplyDeliveryMode<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelPreviewStreamMode: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelPreviewStreamMode');
export type resolveChannelPreviewStreamMode<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelProgressDraftMaxLines: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelProgressDraftMaxLines');
export type resolveChannelProgressDraftMaxLines<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelStreamingBlockEnabled: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelStreamingBlockEnabled');
export type resolveChannelStreamingBlockEnabled<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelStreamingChunkMode: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelStreamingChunkMode');
export type resolveChannelStreamingChunkMode<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelStreamingPreviewChunk: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelStreamingPreviewChunk');
export type resolveChannelStreamingPreviewChunk<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelStreamingPreviewNativeToolProgress: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelStreamingPreviewNativeToolProgress');
export type resolveChannelStreamingPreviewNativeToolProgress<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelStreamingPreviewNativeToolProgressAllowFrom: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelStreamingPreviewNativeToolProgressAllowFrom');
export type resolveChannelStreamingPreviewNativeToolProgressAllowFrom<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveChannelStreamingPreviewToolProgress: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveChannelStreamingPreviewToolProgress');
export type resolveChannelStreamingPreviewToolProgress<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveOutboundSendDep: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveOutboundSendDep');
export type resolveOutboundSendDep<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const resolveTranscriptBackedChannelFinalText: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#resolveTranscriptBackedChannelFinalText');
export type resolveTranscriptBackedChannelFinalText<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const sanitizeForPlainText: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#sanitizeForPlainText');
export type sanitizeForPlainText<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const selectLongerFinalText: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#selectLongerFinalText');
export type selectLongerFinalText<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const sendDurableMessageBatch: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#sendDurableMessageBatch');
export type sendDurableMessageBatch<A = any, B = any, C = any, D = any, E = any, F = any> = any;
export const takeMessageIdAfterStop: StubAny = makeStub('openclaw/plugin-sdk/channel-outbound#takeMessageIdAfterStop');
export type takeMessageIdAfterStop<A = any, B = any, C = any, D = any, E = any, F = any> = any;
